language: ruby
sudo: false
cache: bundler
rvm:
- 2.0.0
branches:
  only:
  - master
script: "./travis_deploy.sh "
env:
  secure: eAyjmkDKLbXnGvC75KRNVLoAr6WE7ldT6JGOzOKOfQ9WxhEFgzAXoKZVO4mX4DfDfJbZbCyFmxKqALXGXjaBKwU2eQKeq1g4svBnxGPHmOKFMfVjkSCFag0bppE2JK9VXn70lVYFh8kJHavHgQ2pRYlSb78WfmUKbbB9PSH/rSE=
notifications:
  slack:
    secure: o2ksyDNq6Ea2oHUbUpgICYHAUdZ0QgHSQNqgn/gginNyPYAd2MtS2h7iXVrzSgeXDSNi6WpAvAeOcUnzpA6h6oBkl0YvUTaXJs50IepWfAE4UZPwX9ZFfV8YiwnOCU9ByUTU2L9qeq83W3LuDYY7j6xZJjP5KMLC78TqTKy5pd8=
before_install:
- openssl aes-256-cbc -K $encrypted_2d0ab44f9ad6_key -iv $encrypted_2d0ab44f9ad6_iv
  -in reefpoints_deploy.enc -out ./reefpoints_deploy -d
